### ISSUE TITLE
Inslider did not work

### ISSUE THREAD

**Issue by yilinxia** [yilinxia/arviz_dashboard#4]
Here is my code
`@pn.depends(model_selection1.param.value, model_selection2.param.value, thre_slider.param.value)`

The error I got
```
Traceback (most recent call last):
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/28/kcwvvd8j31n3160270pbl55c0000gn/T/ipykernel_59053/1832266391.py", line 61, in <cell line: 57>
    pn.Row(get_compare_plot,get_bar_plot))
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/panel/layout/base.py", line 630, in __init__
    params['objects'] = [panel(pane) for pane in objects]
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/panel/layout/base.py", line 630, in <listcomp>
    params['objects'] = [panel(pane) for pane in objects]
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/panel/pane/base.py", line 80, in panel
    pane = PaneBase.get_pane_type(obj, **kwargs)(obj, **kwargs)
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/panel/param.py", line 745, in __init__
    self._replace_pane(not self.lazy)
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/panel/param.py", line 794, in _replace_pane
    new_object = self.eval(self.object)
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/panel/param.py", line 777, in eval
    return function(*args, **kwargs)
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/param/parameterized.py", line 400, in _depends
    return func(*args, **kw)
TypeError: get_compare_plot() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1993, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/IPython/core/ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/IPython/core/ultratb.py", line 818, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/IPython/core/ultratb.py", line 736, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/stack_data/core.py", line 698, in lines
    pieces = self.included_pieces
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/stack_data/core.py", line 645, in included_pieces
    scope_pieces = self.scope_pieces
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/stack_data/core.py", line 585, in scope_pieces
    for piece in self.source.pieces
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/stack_data/core.py", line 90, in pieces
    return list(self._clean_pieces())
  File "/Users/yilinxia/opt/miniconda3/envs/arviz/lib/python3.8/site-packages/stack_data/core.py", line 114, in _clean_pieces
    raise AssertionError("Pieces mismatches: %s" % mismatches)
AssertionError: Pieces mismatches: [{681, 682}, {696, 697}, {709, 710}, {715, 716}]
```

Other similar issues I found 
* https://bytemeta.vip/repo/EarthBigData/openSAR/issues/7
* https://github.com/holoviz/hvplot/issues/744

**Comment by yilinxia** [comment]
after install `hvplot`, the problem get solved
